### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by dkuhnke** [Morgan-Kennedy/MKParallaxView#1]
Hi, what is the required iOS version for your MKParallaxView? Your sample project does not work with iOS 6.1 on simulator. Thx Daniel

**Comment by Morgan-Kennedy** [comment]
Oh, I never thought to test it on a simulator to see what happens.

Essentially, it utilises the device's gyro, so it shouldn't work on a
simulator... but it shouldn't crash either. I'll check it out. Thanks :)

**Comment by Morgan-Kennedy** [comment]
Yeah, it just acts as a normal image view on my simulator. I'm running it on a 6.1 simulator. Not crashing. Just acting like a normal image.

Pull it up on a device to see this baby in action :)
